name: validate
run-name: validate

on:
  pull_request:
    branches: ["*"]
    #paths-ignore:
  push:
    branches: [main]

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: validate (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            pesterScope: CrossPlatform
          - os: windows-latest
            pesterScope: WindowsOnly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - shell: pwsh # install dependencies
        run: .\Build\build.ps1 -ResolveDependency -TaskList 'Init'

      - shell: pwsh # stage module
        run: .\Build\build.ps1 -TaskList 'CombineFunctionsAndStage'

      - shell: pwsh # psscriptanalyzer
        run: .\Build\build.ps1 -TaskList 'Analyze'

      - shell: pwsh # pester
        run: .\Build\build.ps1 -TaskList 'Test' -Properties @{ PesterScope = '${{ matrix.pesterScope }}' }

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Pester Results (${{ matrix.os }})
          path: "Artifacts/**/Test-*.xml"
          if-no-files-found: error
