name: validate
run-name: validate

on:
  pull_request:
    branches: ["*"]
    #paths-ignore:
  push:
    branches: [main]

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: validate (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            pesterScope: CrossPlatform
          - os: windows-latest
            pesterScope: WindowsOnly
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - shell: pwsh # install dependencies
        run: .\Build\build.ps1 -ResolveDependency -TaskList 'Init'

      - shell: pwsh # stage module
        run: .\Build\build.ps1 -TaskList 'CombineFunctionsAndStage'

      - shell: pwsh # psscriptanalyzer
        run: .\Build\build.ps1 -TaskList 'Analyze'

      - shell: pwsh # pester
        run: .\Build\build.ps1 -TaskList 'Test' -Properties @{ PesterScope = '${{ matrix.pesterScope }}' }

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Pester Results (${{ matrix.os }})
          path: "Artifacts/**/Test-*.xml"
          if-no-files-found: error

      - name: Publish Pester results
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: always()
        with:
          name: Pester Tests (${{ matrix.os }})
          path: Artifacts/**/Test-*.xml
          reporter: java-junit
          fail-on-error: false
